using AlgorithmVisualizer.Core.DataStructures.Vector;
using AlgorithmVisualizer.Core.Simulation;
using AlgorithmVisualizer.Core.Simulation.Contracts;

namespace AlgorithmVisualizer.Core.MachineLearning.Supervised.DecisionTree;

/// <summary>
/// From-scratch binary classification tree. Candidate thresholds are generated by an
/// explicit insertion-sort over example indexes; impurity, partitioning, recursion and
/// prediction are all implemented here without framework sorting/tree/ML helpers.
/// </summary>
public sealed class DecisionTreeSimulation : SimulationAlgorithmBase
{
    private ManualVector[] _features = [];
    private int[] _labels = [];
    private DecisionTreeCriterion _criterion = DecisionTreeCriterion.Gini;
    private int _maxDepth = 3;
    private double _minimumGain = 1e-9d;
    private Node[] _nodes = [];
    private int _nodeCount;
    private DecisionTreePhase _phase = DecisionTreePhase.Ready;
    private int _currentNodeId = -1;
    private int _candidateFeature = -1;
    private double _candidateThreshold;
    private double _candidateGain;
    private int _candidateLeftCount;
    private int _candidateRightCount;
    private string _focusText = "Ready.";

    public DecisionTreeSimulation(ISimulationRuntime simulationRuntime) : base(simulationRuntime)
    {
        Configure(new DecisionTreeConfiguration(
            [[1d,1d],[1.4d,2d],[2d,1.3d],[4d,3.8d],[4.6d,4.2d],[5.2d,3.4d]],
            [0,0,0,1,1,1]));
    }

    public void Configure(DecisionTreeConfiguration configuration)
    {
        ArgumentNullException.ThrowIfNull(configuration);
        Validate(configuration);
        _features = new ManualVector[configuration.Features.Length];
        for (var i = 0; i < configuration.Features.Length; i++)
        {
            var vector = new ManualVector(configuration.Features[i].Length);
            vector.CopyFrom(configuration.Features[i]);
            _features[i] = vector;
        }
        _labels = Copy(configuration.Labels);
        _criterion = configuration.Criterion;
        _maxDepth = configuration.MaxDepth;
        _minimumGain = configuration.MinimumGain;
        ResetState();
    }

    public DecisionTreeSnapshot CreateSnapshot() => new(
        CopyFeatures(), Copy(_labels), SnapshotNodes(), _criterion, _phase, _currentNodeId,
        _candidateFeature, _candidateThreshold, _candidateGain, _candidateLeftCount,
        _candidateRightCount, _focusText);

    public async Task<DecisionTreeRunResult> ExecuteAsync(CancellationToken cancellationToken = default)
    {
        ResetState();
        var all = new int[_features.Length];
        for (var i = 0; i < all.Length; i++) all[i] = i;
        _focusText = $"Start with {_features.Length} labeled examples. Find the feature threshold that reduces {_criterion.ToString().ToLowerInvariant()} impurity the most.";
        await NextStepAsync(_focusText, cancellationToken);
        await BuildNodeAsync(all, 0, cancellationToken);
        _phase = DecisionTreePhase.Complete;
        _currentNodeId = -1;
        _candidateFeature = -1;
        _focusText = "Tree complete. A prediction now follows one threshold question per level until it reaches a leaf.";
        await NextStepAsync(_focusText, cancellationToken);

        var correct = 0;
        for (var i = 0; i < _features.Length; i++) if (Predict(_features[i].CopyValues()) == _labels[i]) correct++;
        var root = _nodeCount == 0 ? null : _nodes[0];
        var leaves = 0;
        var depth = 0;
        for (var i = 0; i < _nodeCount; i++) { if (_nodes[i].IsLeaf) leaves++; if (_nodes[i].Depth > depth) depth = _nodes[i].Depth; }
        return new DecisionTreeRunResult(CopyFeatures(), Copy(_labels), SnapshotNodes(), _criterion,
            root?.SplitFeature ?? -1, root?.SplitThreshold ?? 0d, root?.Gain ?? 0d,
            depth, leaves, correct,
            $"Built a {leaves}-leaf decision tree with {correct}/{_features.Length} training examples classified correctly.");
    }

    public int Predict(IReadOnlyList<double> featureValues)
    {
        ArgumentNullException.ThrowIfNull(featureValues);
        if (_nodeCount == 0) throw new InvalidOperationException("Build the tree before predicting.");
        if (featureValues.Count != _features[0].Dimension) throw new ArgumentException("Prediction dimension must match the training data.", nameof(featureValues));
        var node = _nodes[0];
        while (!node.IsLeaf)
        {
            var nextId = featureValues[node.SplitFeature] <= node.SplitThreshold ? node.LeftId : node.RightId;
            if (nextId < 0 || nextId >= _nodeCount) break;
            node = _nodes[nextId];
        }
        return node.Prediction;
    }

    private async Task<int> BuildNodeAsync(int[] indexes, int depth, CancellationToken token)
    {
        token.ThrowIfCancellationRequested();
        var nodeId = AddNode(indexes, depth);
        var node = _nodes[nodeId];
        _currentNodeId = nodeId;
        _phase = DecisionTreePhase.InspectingNode;
        node.State = DecisionTreeNodeState.Active;
        _focusText = $"Node {nodeId}: {indexes.Length} examples, class 0 = {node.ZeroCount}, class 1 = {node.OneCount}, impurity = {Format(node.Impurity)}.";
        await NextStepAsync(_focusText, token);

        if (node.Impurity <= 1e-12d || depth >= _maxDepth || indexes.Length < 2)
        {
            MarkLeaf(node, node.Impurity <= 1e-12d ? "already pure" : depth >= _maxDepth ? "maximum depth reached" : "too few examples to split");
            await NextStepAsync(_focusText, token);
            return nodeId;
        }

        var best = new SplitCandidate(-1, 0d, 0d, [], []);
        for (var feature = 0; feature < _features[0].Dimension; feature++)
        {
            var sorted = Copy(indexes);
            SortIndexesByFeature(sorted, feature);
            for (var pos = 0; pos < sorted.Length - 1; pos++)
            {
                var leftValue = _features[sorted[pos]][feature];
                var rightValue = _features[sorted[pos + 1]][feature];
                if (Math.Abs(leftValue - rightValue) <= 1e-12d) continue;
                var threshold = (leftValue + rightValue) / 2d;
                Partition(indexes, feature, threshold, out var left, out var right);
                if (left.Length == 0 || right.Length == 0) continue;
                var gain = node.Impurity - WeightedImpurity(left, right, indexes.Length);
                _phase = DecisionTreePhase.EvaluatingSplit;
                _candidateFeature = feature;
                _candidateThreshold = threshold;
                _candidateGain = gain;
                _candidateLeftCount = left.Length;
                _candidateRightCount = right.Length;
                _focusText = $"Try feature {feature + 1} ≤ {Format(threshold)}: {left.Length} go left, {right.Length} go right, gain = {Format(gain)}.";
                await NextStepAsync(_focusText, token);
                if (gain > best.Gain + 1e-12d) best = new SplitCandidate(feature, threshold, gain, left, right);
            }
        }

        if (best.Feature < 0 || best.Gain <= _minimumGain)
        {
            MarkLeaf(node, "no candidate split improves impurity enough");
            await NextStepAsync(_focusText, token);
            return nodeId;
        }

        node.SplitFeature = best.Feature;
        node.SplitThreshold = best.Threshold;
        node.Gain = best.Gain;
        node.State = DecisionTreeNodeState.Split;
        _phase = DecisionTreePhase.Splitting;
        _candidateFeature = best.Feature;
        _candidateThreshold = best.Threshold;
        _candidateGain = best.Gain;
        _candidateLeftCount = best.Left.Length;
        _candidateRightCount = best.Right.Length;
        _focusText = $"Choose feature {best.Feature + 1} ≤ {Format(best.Threshold)} because it gives the largest impurity reduction: {Format(best.Gain)}.";
        await NextStepAsync(_focusText, token);

        node.LeftId = await BuildNodeAsync(best.Left, depth + 1, token);
        node.RightId = await BuildNodeAsync(best.Right, depth + 1, token);
        _currentNodeId = nodeId;
        return nodeId;
    }

    private int AddNode(int[] indexes, int depth)
    {
        EnsureNodeCapacity(_nodeCount + 1);
        var zero = 0; var one = 0;
        for (var i = 0; i < indexes.Length; i++) { if (_labels[indexes[i]] == 0) zero++; else one++; }
        var node = new Node(_nodeCount, depth, Copy(indexes), zero, one, one > zero ? 1 : 0, Impurity(zero, one));
        _nodes[_nodeCount] = node;
        _nodeCount++;
        return node.Id;
    }

    private void MarkLeaf(Node node, string reason)
    {
        node.IsLeaf = true;
        node.State = DecisionTreeNodeState.Leaf;
        _focusText = $"Node {node.Id} becomes a leaf predicting class {node.Prediction}: {reason}.";
    }

    private double WeightedImpurity(int[] left, int[] right, int total)
    {
        CountClasses(left, out var l0, out var l1); CountClasses(right, out var r0, out var r1);
        return (left.Length / (double)total) * Impurity(l0, l1) + (right.Length / (double)total) * Impurity(r0, r1);
    }

    private double Impurity(int zero, int one)
    {
        var total = zero + one;
        if (total == 0) return 0d;
        var p0 = zero / (double)total; var p1 = one / (double)total;
        if (_criterion == DecisionTreeCriterion.Gini) return 1d - (p0 * p0) - (p1 * p1);
        return EntropyPart(p0) + EntropyPart(p1);
    }

    private static double EntropyPart(double p) => p <= 0d ? 0d : -p * Math.Log2(p);
    private void CountClasses(int[] indexes, out int zero, out int one) { zero = 0; one = 0; for (var i = 0; i < indexes.Length; i++) { if (_labels[indexes[i]] == 0) zero++; else one++; } }

    private void Partition(int[] source, int feature, double threshold, out int[] left, out int[] right)
    {
        var leftCount = 0;
        for (var i = 0; i < source.Length; i++) if (_features[source[i]][feature] <= threshold) leftCount++;
        left = new int[leftCount]; right = new int[source.Length - leftCount];
        var li = 0; var ri = 0;
        for (var i = 0; i < source.Length; i++) { if (_features[source[i]][feature] <= threshold) left[li++] = source[i]; else right[ri++] = source[i]; }
    }

    private void SortIndexesByFeature(int[] indexes, int feature)
    {
        for (var i = 1; i < indexes.Length; i++)
        {
            var key = indexes[i]; var j = i - 1;
            while (j >= 0 && _features[indexes[j]][feature] > _features[key][feature]) { indexes[j + 1] = indexes[j]; j--; }
            indexes[j + 1] = key;
        }
    }

    private void EnsureNodeCapacity(int required)
    {
        if (_nodes.Length >= required) return;
        var next = new Node[Math.Max(required, _nodes.Length == 0 ? 8 : _nodes.Length * 2)];
        for (var i = 0; i < _nodeCount; i++) next[i] = _nodes[i];
        _nodes = next;
    }

    private void ResetState()
    {
        _nodes = []; _nodeCount = 0; _phase = DecisionTreePhase.Ready; _currentNodeId = -1;
        _candidateFeature = -1; _candidateThreshold = 0d; _candidateGain = 0d; _candidateLeftCount = 0; _candidateRightCount = 0; _focusText = "Ready.";
    }

    private DecisionTreeNodeSnapshot[] SnapshotNodes()
    {
        var result = new DecisionTreeNodeSnapshot[_nodeCount];
        for (var i = 0; i < _nodeCount; i++)
        {
            var n = _nodes[i];
            result[i] = new DecisionTreeNodeSnapshot(n.Id,n.Depth,Copy(n.ExampleIndices),n.ZeroCount,n.OneCount,n.Prediction,n.Impurity,n.IsLeaf,n.SplitFeature,n.SplitThreshold,n.Gain,n.LeftId,n.RightId,n.State);
        }
        return result;
    }
    private double[][] CopyFeatures() { var result = new double[_features.Length][]; for (var i=0;i<_features.Length;i++) result[i]=_features[i].CopyValues(); return result; }
    private static int[] Copy(int[] source) { var result = new int[source.Length]; for (var i=0;i<source.Length;i++) result[i]=source[i]; return result; }
    private static string Format(double value) => Math.Abs(value) < 1e-12d ? "0" : value.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture);

    private static void Validate(DecisionTreeConfiguration c)
    {
        if (c.Features is null || c.Labels is null) throw new ArgumentException("Features and labels are required.");
        if (c.Features.Length < 2 || c.Features.Length != c.Labels.Length) throw new ArgumentException("Use at least two examples and one label per example.");
        var dimension = c.Features[0]?.Length ?? 0;
        if (dimension < 1) throw new ArgumentException("Examples need at least one feature.");
        for (var i=0;i<c.Features.Length;i++)
        {
            if (c.Features[i] is null || c.Features[i].Length != dimension) throw new ArgumentException("All examples must have the same feature dimension.");
            for (var d=0;d<dimension;d++) if (!double.IsFinite(c.Features[i][d])) throw new ArgumentException("Feature values must be finite.");
            if (c.Labels[i] is not (0 or 1)) throw new ArgumentException("This teaching tree supports binary labels 0 and 1.");
        }
        if (c.MaxDepth is < 1 or > 6) throw new ArgumentOutOfRangeException(nameof(c.MaxDepth), "Teaching max depth must be between 1 and 6.");
        if (!double.IsFinite(c.MinimumGain) || c.MinimumGain < 0d) throw new ArgumentOutOfRangeException(nameof(c.MinimumGain));
    }

    private sealed class Node(int id,int depth,int[] exampleIndices,int zeroCount,int oneCount,int prediction,double impurity)
    {
        public int Id { get; }=id; public int Depth { get; }=depth; public int[] ExampleIndices { get; }=exampleIndices;
        public int ZeroCount { get; }=zeroCount; public int OneCount { get; }=oneCount; public int Prediction { get; }=prediction; public double Impurity { get; }=impurity;
        public bool IsLeaf { get; set; } public int SplitFeature { get; set; }=-1; public double SplitThreshold { get; set; } public double Gain { get; set; }
        public int LeftId { get; set; }=-1; public int RightId { get; set; }=-1; public DecisionTreeNodeState State { get; set; }=DecisionTreeNodeState.Stored;
    }
    private sealed record SplitCandidate(int Feature,double Threshold,double Gain,int[] Left,int[] Right);
}
